import { anilistClient } from '@/services/anilistGraphql'
import '@/styles/globals.css'
import { getAnimesPerPage } from '@/utils/getAnimesPerPage'
import { gql } from '@apollo/client'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  const data = await getAnimesPerPage(1, 10)

  console.log(data)

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
