import { Header } from '@/components/Header'
import '@/styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className='flex bg-slate-900'>
        <Header />
        {children}
      </body>
    </html>
  )
}
