import { anilistClient } from '@/services/anilistGraphql'
import '@/styles/globals.css'
import { getAnimesPerPage } from '@/utils/getAnimesPerPage'
import { gql } from '@apollo/client'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IAnime {
  id: number
  title: {
    english: string
    native: string
  }
  coverImage: {
    medium: string
  }
  episodes: number
  seasonYear: number
  status: string
  format: string
}

type AnimeListType = IAnime[]

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  const data: AnimeListType = await getAnimesPerPage(1, 10)

  console.log("data", data[3].title.english)
  console.log("data", data[3].format)
  console.log("data", data[3].coverImage.medium)

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
